---

- block:
    - include_tasks: context.yml

    - include_tasks: users.yml

    - include_tasks: sync_tool.yml

    - include_tasks: share_dirs.yml

  when: want_share

- name: set has_share
  set_fact:
    has_share: "{{ want_share }}"
