---

- name: groups
  group:
    name: "{{ group.name }}"
    state: "{{ group.state | default('present') }}"
    gid: "{{ group.gid | default(omit) }}"
    system: "{{ group.system | default('no') }}"
  loop: "{{ share_groups }}"
  loop_control:
    loop_var: group


- include_tasks: user.yml
  loop: "{{ share_users }}"
  loop_control:
    loop_var: user
